# Generated by Django 5.2.8 on 2025-11-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='referencia',
            field=models.CharField(default='Geral', max_length=50, verbose_name='Referência (Ex: Outubro/2025)'),
            preserve_default=False,
        ),
    ]
