# Generated by Django 5.2.8 on 2025-11-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_pagamento_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='referencia',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='ano',
            field=models.IntegerField(choices=[(2025, '2025'), (2026, '2026'), (2027, '2027')], default=2025, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='mes',
            field=models.CharField(choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], default='01', max_length=2, verbose_name='Mês'),
        ),
    ]
