# Generated by Django 5.2.8 on 2025-11-27 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_remove_pagamento_referencia_pagamento_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='data_aula',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
