# Generated by Django 5.2.8 on 2025-11-28 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_alter_presenca_data_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academia.curso'),
        ),
    ]
