# Generated by Django 5.2.8 on 2025-11-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_pagamento_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/', verbose_name='Imagem do Card'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='horario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Horário (Ex: Terça 14h)'),
        ),
    ]
