# Generated by Django 5.2.8 on 2025-11-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0006_curso_descricao_curso_imagem_matricula_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(default='', max_length=20, verbose_name='WhatsApp (apenas números)'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(choices=[('PIX', 'Pix'), ('CC', 'Cartão de Crédito'), ('CD', 'Cartão de Débito'), ('DIN', 'Dinheiro')], default='PIX', max_length=3, verbose_name='Forma de Pagamento'),
        ),
    ]
