# Generated by Django 5.2.8 on 2025-12-01 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0007_aluno_telefone_pagamento_metodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('qtd_alunos', models.IntegerField(default=0, verbose_name='Qtd. Alunos Computados')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor a Pagar')),
                ('pago', models.BooleanField(default=False)),
                ('data_pagamento_realizado', models.DateTimeField(blank=True, null=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.professor')),
            ],
        ),
    ]
