# Generated by Django 5.2.8 on 2025-12-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0008_pagamentoprofessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='contato_responsavel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zap do Responsável'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço Completo'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='membro_metodista',
            field=models.BooleanField(default=False, verbose_name='É membro da Igreja Metodista?'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Responsável'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='outra_igreja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Se não, qual igreja?'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
    ]
