# Generated by Django 5.2.8 on 2025-12-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0009_aluno_contato_responsavel_aluno_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_alunos/', verbose_name='Foto do Aluno'),
        ),
    ]
