# Generated by Django 5.2.8 on 2025-12-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0010_aluno_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='criado_por_admin',
            field=models.BooleanField(default=False, verbose_name='Criado pela Secretaria?'),
        ),
    ]
