# Generated by Django 5.2.8 on 2025-12-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0011_aluno_criado_por_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='horario',
        ),
        migrations.AddField(
            model_name='matricula',
            name='dia_semana',
            field=models.CharField(blank=True, choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado')], max_length=3, null=True, verbose_name='Dia'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='hora_aula',
            field=models.CharField(blank=True, choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00')], max_length=5, null=True, verbose_name='Hora'),
        ),
    ]
