# Generated by Django 5.2.8 on 2025-12-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0012_remove_matricula_horario_matricula_dia_semana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título (Ex: Cobrança Leve)')),
                ('texto', models.TextField(verbose_name='Texto da Mensagem')),
            ],
        ),
        migrations.AlterField(
            model_name='matricula',
            name='hora_aula',
            field=models.CharField(blank=True, choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00')], max_length=5, null=True, verbose_name='Hora'),
        ),
    ]
