# Generated by Django 5.2.8 on 2025-12-04 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0013_mensagempadrao_alter_matricula_hora_aula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateField(default=datetime.date.today, verbose_name='Data do Pagamento'),
        ),
    ]
