# Generated by Django 5.2.8 on 2025-12-05 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0014_alter_pagamento_data_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_doador', models.CharField(max_length=100, verbose_name='Nome do Doador')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contato')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Doação')),
                ('data_doacao', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('metodo', models.CharField(choices=[('PIX', 'Pix'), ('DIN', 'Dinheiro'), ('TRA', 'Transferência')], default='PIX', max_length=3)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo/Obs')),
                ('comprovante', models.ImageField(blank=True, null=True, upload_to='doacoes/')),
            ],
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='endereco',
        ),
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(default='Tanguá', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='eh_bolsista',
            field=models.BooleanField(default=False, verbose_name='É Bolsista? (Isento de Mensalidade)'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='logradouro',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Rua/Av/Logradouro'),
        ),
    ]
