# Generated by Django 5.2.8 on 2025-12-05 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0015_doacao_remove_aluno_endereco_aluno_bairro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição (Ex: Conta de Luz)')),
                ('categoria', models.CharField(choices=[('FIXA', 'Despesa Fixa'), ('VAR', 'Despesa Variável'), ('MAN', 'Manutenção/Material')], default='FIXA', max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_despesa', models.DateField(default=datetime.date.today, verbose_name='Data do Pagamento')),
                ('comprovante', models.ImageField(blank=True, null=True, upload_to='despesas/')),
            ],
        ),
    ]
