# Generated by Django 5.2.8 on 2025-12-15 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0016_despesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='curso',
        ),
        migrations.AddField(
            model_name='presenca',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.matricula'),
        ),
    ]
