# Generated by Django 5.2.8 on 2025-12-16 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0017_remove_presenca_aluno_remove_presenca_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='matricula',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='academia.matricula'),
            preserve_default=False,
        ),
    ]
