# Generated by Django 5.2.8 on 2025-12-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0018_alter_presenca_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Curso Ativo? (Aceita novas matrículas)'),
        ),
    ]
