# Generated by Django 5.2.8 on 2025-12-19 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0019_curso_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_matricula',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Matrícula'),
        ),
    ]
