# Generated by Django 5.2.8 on 2025-12-19 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0020_aluno_data_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='data_inicio',
            field=models.DateField(default=datetime.date.today, verbose_name='Data da Matrícula'),
        ),
    ]
