# Generated by Django 5.2.8 on 2025-12-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0021_alter_matricula_data_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='busca_normalizada',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
