# Generated by Django 5.2.8 on 2025-12-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0022_aluno_busca_normalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='nome_pagante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Pagante (Quem pagou?)'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='membro_metodista',
            field=models.BooleanField(default=False, verbose_name='É membro da Igreja Metodista Central de Tanguá?'),
        ),
    ]
