# Generated by Django 5.2.8 on 2025-12-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0023_pagamento_nome_pagante_alter_aluno_membro_metodista'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
